fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        always_run: true
        pass_filenames: false
        verbose: true
        args:
          - "."
          - --skip-glob
          - .venv/*

  - repo: https://github.com/pycqa/pylint
    rev: v2.15.8
    hooks:
      - id: pylint
        name: pylint linter
        always_run: true
        pass_filenames: false
        exclude: ^generated/
        args:
          - --fail-under=4
          - "."
